#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Tool: generate `my/MY_INDEX.md` — **every document in this project that is yours**

## Why this tool exists

🔴 **Measured case (reported by the principal, 2026-08-27): a project adopted this framework
and then stopped maintaining its own file index — its `file_index.md` contains ⛔ not one
research-related entry.**

⚠️ **Mechanism: `file_index.md` began life in a predecessor project as the table for
"research plan versions and supporting documents". When it was refined into the framework its
contents became entirely the framework's own, ⛔ and the name did not change.**
**So a new user sees a file called "file index" and assumes it is theirs —**
🔴 **and then either registers their documents in it (lost at the next upgrade) or stops
registering anything (what actually happened).**

**⇒ The framework did ⛔ not merely neglect the user's index; it displaced a mechanism that
already existed.**

## The criterion: **list everything the framework does ⛔ not own**

⛔ **⚠️ This deliberately does ⛔ not enumerate "what counts as a research document".**
🔴 **A list of "what to include" is a whitelist (`R-21`): users keep inventing new folders,
and every folder not on the list silently fails to appear in the index.**

⚠️ **A predecessor project's generator had exactly that shape, and its author wrote the
sentence themselves: "a hand-written index misses files, ⛔ and a generator misses directories."**

→ **This tool scans everything and ⛔ then subtracts the names the framework owns.**
**The single home for those names is the replaceable list in `upgrade.py` — ⛔ never a
second copy here.**

## Descriptions are maintained by an AI, ⛔ not guessed by code

⚠️ **The principal's practice: the descriptions in a research index have always been
maintained by the research AI.**
**⛔ And code cannot extract anything meaningful from `.docx` / `.pdf` / `.xlsx`.**

→ **The file list is generated (⛔ it cannot drift); the descriptions live in
`my/MY_INDEX_notes.json`, maintained by an AI.**
🔴 **Files with no description are ⛔ not hidden — they get their own section** —
**⛔ an index that looks complete while missing half the files is worse than no index.**

Exit codes: 0 generated | 1 file problem | 2 could not check
"""
import argparse
import io
import json
import pathlib
import sys

HERE = pathlib.Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))
from _common import _force_utf8                            # noqa: E402
from framework_config import load, excluded                # noqa: E402
# 🔴 **Which names the framework owns: the single home is `upgrade.py`.**
#    ⚠️ **⛔ Never restated here** — two hand-written lists always diverge
#    (constitution §3.2, §6.4).
#    ⛔ **And deliberately ⛔ not in `governance_config.json`: that file is the user's,
#    and "what an upgrade may replace" must not be decided by a user setting.**
from upgrade import FRAMEWORK_DIRS, FRAMEWORK_FILES        # noqa: E402

_force_utf8()

HEADER = """# My file index (**what in this project is yours**)

> 🔴 **⛔ Generated by a program. ⛔ Do not edit by hand.** Regenerate with:
> `python scripts/harness/tool_my_index.py`
>
> **Descriptions live in `my/MY_INDEX_notes.json`** (edit that by hand, or have an AI maintain it).
>
> ⚠️ **The criterion is "everything the framework does ⛔ not own", ⛔ not a list of
> "what to include"** — **a list of what to include is a whitelist, and users keep
> inventing new folders.**
>
> ⛔ **The framework's own index is `file_index.md`, ⛔ and that one is replaced wholesale
> on upgrade.**
"""


# macOS Finder writes `.DS_Store` into any folder it opens; upgrade.py already treats it as transient.
OS_METADATA_NAMES = frozenset({".DS_Store"})


def framework_owned(rel):
    """Is this relative path something the framework owns?"""
    top = rel.split("/", 1)[0]
    return top in FRAMEWORK_DIRS or rel in FRAMEWORK_FILES


def collect(root, cfg):
    """Return the relative paths, **sorted as strings**.

    🔴 **Measured case (2026-08-27, at the moment v1.4.1 was released, the principal's machine):**
    **the old line was `sorted(root.rglob("*"))` — ⛔ that sorts `Path` objects.**
    **⚠️ `WindowsPath` comparison casefolds first; `PosixPath` ⛔ does not.**
    **So `PROJECT.md` sorts before `corpus/` on Linux and after it on Windows.**

    ⛔ **Consequence: the index generated on Linux and shipped with v1.4.1 reported
    `MY_INDEX_STALE` on the very first run on the principal's Windows machine —
    and what it reported was ⛔ not "the index is stale" but "your operating system is not
    the one that generated it".**
    🔴 **A criterion that fires on a correct state teaches people to ignore it (`R-19`) —
    and it had already forced a manual workaround mid-release.**

    ⇒ **The sort key is now the relative posix string. ⛔ Never the `Path` object.**
    """
    files = []
    for p in root.rglob("*"):
        if not p.is_file():
            continue
        if p.name in OS_METADATA_NAMES:
            continue                      # ⛔ Finder metadata is not a user file (Mac field test 2026-09-11)
        if excluded(p, root, cfg):
            continue
        rel = p.relative_to(root).as_posix()
        if framework_owned(rel):
            continue
        if rel in (cfg.get("my_index", "my/MY_INDEX.md"),):
            continue                      # ⛔ the index does not list itself
        if any(pathlib.PurePosixPath(rel).match(g)
               for g in cfg.get("my_index_exclude", [])):
            continue                      # ⛔ files the framework itself produces
        files.append(rel)
    # ⛔ **Sort strings, ⛔ never Path objects.** See this function's docstring.
    return sorted(files)


def render(root, cfg):
    """Produce the index text. Returns (text, stats, error).

    🔴 **The sensor and this tool share this one function; ⛔ neither writes its own.**
    ⚠️ **If two generators differ anywhere, the "is the index stale" criterion would say
    stale forever, ⛔ while the real cause is that the two programs are not the same.**
    """
    notes_p = root / cfg.get("my_index_notes", "my/MY_INDEX_notes.json")
    notes = {}
    if notes_p.is_file():
        try:
            notes = json.loads(notes_p.read_text(encoding="utf-8"))
        except Exception as e:                              # noqa: BLE001
            # ⛔ The R-33 position: an unreadable notes file must ⛔ not fall through
            #    to "there are no descriptions".
            return None, None, (f"{notes_p.name} could not be parsed: {e}"
                                " — **⚠️ that is not the same as "
                                "'there are no descriptions'**")
    notes = {k: v for k, v in notes.items() if not k.startswith("_")}

    files = collect(root, cfg)
    described = [f for f in files if notes.get(f)]
    plain = [f for f in files if not notes.get(f)]
    # 🔴 A description pointing at a file that does not exist is a dangling reference,
    #    ⛔ and it must be visible.
    # 🔴 **A note absent from the scan has two possible causes, ⛔ carrying very
    #    different information.** ⚠️ **Before v1.4.4 both printed "the file does not
    #    exist"** — ⛔ **and acting on that (deleting the note) does not fail, ⇒ nobody
    #    ever finds out the message lied.**
    #    **Triggering case (Project D, 2026-09-02): `archive/` sits in
    #    `my_index_exclude`, so a retired file that really exists printed as missing.**
    #    🔴 **⇒ Look at the disk before saying something does not exist.**
    scanned = set(files)
    dangling, excluded = [], []
    for k in sorted(notes):
        if k in scanned:
            continue
        if (root / k).exists():
            excluded.append(k)      # ⚠️ the file is there, ⛔ just outside the index scan
        else:
            dangling.append(k)      # 🔴 the file really is gone ⇒ a dangling reference

    out = [HEADER, ""]
    out.append(f"**{len(files)} files | {len(described)} described | "
               f"{len(plain)} not yet described**")
    out.append("")
    out.append("---")
    out.append("")
    out.append("## Described")
    out.append("")
    if described:
        out.append("| File | Description |")
        out.append("|---|---|")
        for f in described:
            out.append(f"| `{f}` | {notes[f]} |")
    else:
        out.append("**(None yet. ⚠️ That is the result of taking stock — "
                   "every file is in the next section.)**")
    out.append("")
    out.append("## ⚠️ Not yet described")
    out.append("")
    if plain:
        out.append("🔴 **⛔ They are not hidden.** "
                   "Have an AI write the descriptions into `my/MY_INDEX_notes.json`, "
                   "then run this tool again.")
        out.append("")
        for f in plain:
            out.append(f"- `{f}`")
    else:
        out.append("**(None. ⚠️ The result of taking stock, ⛔ not the absence of it.)**")
    if dangling:
        out.append("")
        out.append("## 🔴 Descriptions pointing at files that do not exist")
        out.append("")
        out.append("⚠️ **The file was moved or renamed, ⛔ and the description stayed behind.**")
        out.append("")
        for f in dangling:
            out.append(f"- `{f}`")
    if excluded:
        out.append("")
        out.append("## ⚠️ Described, and outside the index's scan")
        out.append("")
        out.append("**The file does exist, ⛔ and `my_index_exclude` keeps it out of the "
                   "index** — ⇒ the description is fine to keep, ⛔ but the index will "
                   "never list it.")
        out.append("")
        for f in excluded:
            out.append(f"- `{f}`")
    out.append("")

    return ("\n".join(out),
            {"files": len(files), "described": len(described),
             "not yet described": len(plain), "notes pointing at missing files": dangling,
             "described but excluded": excluded},
            None)


def main(argv=None):
    ap = argparse.ArgumentParser(description="Generate this project's my/MY_INDEX.md")
    ap.add_argument("--root", default=None, help="project root to index")
    args = ap.parse_args(argv)
    root = pathlib.Path(args.root).resolve() if args.root else HERE.parents[1]
    cfg = load(root)
    idx = root / cfg.get("my_index", "my/MY_INDEX.md")
    text, stats, err = render(root, cfg)
    if err:
        print(f"[FAIL] {err} — **⛔ nothing was generated.**")
        return 1
    idx.parent.mkdir(parents=True, exist_ok=True)
    io.open(idx, "w", encoding="utf-8", newline="\n").write(text)
    print(f"✅ generated {idx.relative_to(root)}")
    print(f"   {stats['files']} files | {stats['described']} described | "
          f"{stats['not yet described']} not yet")
    if stats["notes pointing at missing files"]:
        print("   🔴 descriptions pointing at missing files: "
              f"{len(stats['notes pointing at missing files'])}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
